services:
  frontend:
    build:
      context: ./Calendar.UI/Calendar.UI
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - calendarapi
    networks:
      - productnetwork

  calendarapi:
    build:
      context: ./CalendarAPI/CalendarAPI
      dockerfile: Dockerfile
    ports:
       - "7059:7059"
    depends_on:
      - sqlserver 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - productnetwork
    restart: on-failure

  sqlserver:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql
    networks:
      - productnetwork


networks:
  productnetwork:

volumes:
  sqlvolume:
